name: 'Checkout and run yarn'
description: 'Checks out the branch, sets up Node and installs deps using yarn with cache for speed'
inputs:
  cache-version:
    required: false
    description: 'used for refreshing the cache by simply changing value to something new'
    default: '1'
runs:
  using: 'composite'
  steps:
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: lts/*

    # A repository can have up to 10GB of caches. Once the limit is reached, older caches will be evicted based on when the cache was last accessed. Caches that are not accessed within the last week will also be evicted.
    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ inputs.cache-version }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies
      # install deps only if yarn.lock has changed (https://github.com/actions/cache)
      if: steps.cache-deps.outputs.cache-hit != 'true'
      # install and do not generate a yarn.lock, and if possible used cached packages
      run: yarn install --frozen-lockfile --prefer-offline
      shell: bash

    - name: Generate Tracking Schema
      run: yarn generate-tracking-schema
      shell: bash
